apiVersion: v1
kind: Pod
metadata:
  name: headnode
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: phenix
      image: ghcr.io/sandialabs/sceptre-phenix/phenix:main
      args:
        - phenix
        - ui
        - --hostname-suffixes=-minimega,-phenix
        - --minimega-console
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: host-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: host-tmp-minimega
          mountPath: /tmp/minimega
        - name: host-tmp-phenix
          mountPath: /tmp/phenix
        - name: host-log-phenix
          mountPath: /var/log/phenix
        - name: host-etc-phenix
          mountPath: /etc/phenix
        - name: host-netns
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: host-phenix
          mountPath: /phenix
          mountPropagation: Bidirectional
      readinessProbe:
        exec:
          command: ["phenix", "version"]
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        exec:
          command: ["phenix", "version"]
        initialDelaySeconds: 30
        periodSeconds: 20
    - name: minimega
      image: ghcr.io/sandia-minimega/minimega:master
      env:
        - name: MM_BASE
          value: /tmp/minimega
        - name: MM_FILEPATH
          value: /phenix/images
        - name: MM_PORT
          value: "9000"
        - name: MM_DEGREE
          value: "0"
        - name: MM_CONTEXT
          value: phenix
        - name: MM_LOGLEVEL
          value: info
        - name: MM_LOGFILE
          value: /var/log/phenix/minimega.log
        - name: MM_ABSSNAPSHOT
          value: "true"
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: host-modules
          mountPath: /lib/modules
          readOnly: true
        - name: host-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: host-tmp-minimega
          mountPath: /tmp/minimega
        - name: host-tmp-phenix
          mountPath: /tmp/phenix
        - name: host-log-phenix
          mountPath: /var/log/phenix
        - name: host-netns
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: host-phenix
          mountPath: /phenix
          mountPropagation: Bidirectional
      readinessProbe:
        exec:
          command: ["minimega", "-e", "version"]
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        exec:
          command: ["minimega", "-e", "version"]
        initialDelaySeconds: 30
        periodSeconds: 20
  volumes:
    - name: host-dev
      hostPath:
        path: /dev
    - name: host-modules
      hostPath:
        path: /lib/modules
    - name: host-localtime
      hostPath:
        path: /etc/localtime
        type: File
    - name: host-tmp-minimega
      hostPath:
        path: /tmp/minimega
        type: DirectoryOrCreate
    - name: host-tmp-phenix
      hostPath:
        path: /tmp/phenix
        type: DirectoryOrCreate
    - name: host-log-phenix
      hostPath:
        path: /var/log/phenix
        type: DirectoryOrCreate
    - name: host-etc-phenix
      hostPath:
        path: /etc/phenix
        type: DirectoryOrCreate
    - name: host-netns
      hostPath:
        path: /var/run/netns
        type: DirectoryOrCreate
    - name: host-phenix
      hostPath:
        path: /phenix
        type: DirectoryOrCreate
